# Generated by Django 5.2.7 on 2025-12-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="expiry_date",
        ),
        migrations.AddField(
            model_name="card",
            name="expiry_month",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="card",
            name="expiry_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
