# Generated by Django 5.2.7 on 2025-12-10 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_remove_card_expiry_date_card_expiry_month_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="expiry_month",
        ),
        migrations.RemoveField(
            model_name="card",
            name="expiry_year",
        ),
        migrations.AddField(
            model_name="card",
            name="expiry_date",
            field=models.CharField(max_length=5, null=True),
        ),
    ]
