# Generated by Django 5.2.7 on 2025-12-12 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_remove_card_expiry_month_remove_card_expiry_year_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="card",
            name="is_verified",
        ),
        migrations.RemoveField(
            model_name="card",
            name="verification_code",
        ),
        migrations.AddField(
            model_name="card",
            name="card_password",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
