# Generated by Django 5.2.7 on 2025-12-01 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_customuser_phone_number_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="frist_name",
            new_name="first_name",
        ),
    ]
